application: lukeyear
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /favicon.ico
  static_files: misc/favicon.ico
  upload: misc/favicon.ico

- url: /admin/.*
  script: webapp.py
  login: admin

- url: /(?:index.html)?
  static_files: index.html
  upload: index.html

- url: /.*
  script: webapp.py
